/** Static profession options (in-repo copy; not fetched from external APIs). */
export const PROFESSIONS = [
  "Administrative Support",
  "Chief Executive Officer (CEO)/President",
  "Chief Operating Officer (COO)",
  "Chief Technology Officer (CTO)",
  "Cloud Architect/Engineer",
  "Customer Success Manager",
  "Cybersecurity Specialist",
  "Data Scientist/Analyst/Engineer",
  "Finance and Accounting",
  "Founder/Entrepreneur",
  "Human Resources (HR)",
  "IT Support",
  "Legal Counsel or Support",
  "Marketing and Communications",
  "Operations",
  "Product Manager",
  "Project or Program Manager/Coordinator",
  "Sales Manager/Business Development",
  "Software Developer/Engineer",
  "Student",
  "UI/UX Designer",
  "Other",
] as const;

/** Static industry options (in-repo copy; not fetched from external APIs). */
export const INDUSTRIES = [
  "Artificial Intelligence (AI) and Machine Learning",
  "Augmented Reality (AR) & Virtual Reality (VR)",
  "Blockchain and Cryptocurrency",
  "CleanTech (Clean Technology)",
  "Cloud Computing",
  "Cybersecurity",
  "Data Analytics & Big Data",
  "E-commerce and Retail Technology",
  "EdTech (Educational Technology)",
  "Educational Institution",
  "FinTech (Financial Technology)",
  "Gaming & Entertainment Technology",
  "Government",
  "GreenTech & Environment Technology",
  "HealthTech/MedTech (Healthcare Technology)",
  "Industry Association",
  "Information Technology (IT) Services",
  "Internet of Things (IoT)",
  "Manufacturing & Industrial Technology",
  "Maritime Technology",
  "MaritimeTech",
  "Mobility and Transportation Technology",
  "PropTech (Property Technology)",
  "Quantum Computing",
  "SaaS (Software as a Service)",
  "Service Provider",
  "Smart Home Technology",
  "Tech Sector Partner/Supporter",
  "Telecommunications",
  "Web Development & Digital Services",
  "Other",
] as const;

export const TECHNL_MEMBER_OPTIONS = ["Yes", "No", "Not Sure"] as const;
